add support for reinvocationPolicy
admiraltyio/admiralty pull request #193
Opened 2023-09-07 15:32 UTC by kirillmakhonin-brt

This Pull Requests adds possibility to customize reinvocationPolicy for webhook deployed by HELM chart.
This closes #192 and allows to use admirality in conjunction with other webhooks 

In order to provide backward compatibility - default value is set to `Never` (as it is default for kubernetes)
Docs: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy

2023-09-07 21:43 UTC, kirillmakhonin-brt commented
@adrienjt  could you please review this Pull Request?

2023-09-07 22:07 UTC, adrienjt requested changes
Hi @kirillmakhonin-brt , could you please document the new value in https://github.com/admiraltyio/admiralty/blob/master/charts/multicluster-scheduler/README.md#parameters ?

2023-09-08 14:16 UTC, kirillmakhonin-brt commented
@adrienjt done, please check

2023-09-08 18:56 UTC, adrienjt approved these changes

2023-09-08 18:57 UTC, merged